### ISSUE TITLE
Screenshots on readme

### ISSUE THREAD

**Issue by robwithhair** [rrutt/cb-bread#5]
Would be really handy for folks stumbling across this project to see some screenshots in the read me so they can have a quick look at the UI.

**Comment by rrutt** [comment]
Sounds like a good idea.

Notes for myself on image references in MarkDown:

http://rmarkdown.rstudio.com/authoring_basics.html

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images

**Comment by robwithhair** [comment]
On chrome in github I think you can cut and paste images BTW

**Comment by rrutt** [comment]
I added 50% reduced screen shot PNG images to the 'dev' branch ReadMe, which appears as the default front page here on GitHub.com

I felt this did not justify a new Release tag.
This means that the "Read Me" link in the installed application will link to the prior version of this Read Me page.
However if you are able get the latest version installed and running, you can view the actual screens in the application.

Any future feature enhancement release will link to an updated Read Me page that will include these images.

**Comment by robwithhair** [comment]
Brilliant, thanks @rrutt
